In [77]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split  # separating training data and split data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [78]:
credit_data = pd.read_csv('dataset_credit.csv')

In [79]:
credit_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [80]:
credit_data.shape

(284807, 31)

In [81]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [82]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [83]:
# distribution of legit transactions & fraudulent transactions
credit_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [84]:
# separating the data for analysis
legit = credit_data[credit_data.Class == 0]  # storing into new variables
fraud = credit_data[credit_data.Class == 1]

In [85]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [86]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [87]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [88]:
# compare the values for both transactions
credit_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [89]:
legit.mean()

Time      94838.202258
V1            0.008258
V2           -0.006271
V3            0.012171
V4           -0.007860
V5            0.005453
V6            0.002419
V7            0.009637
V8           -0.000987
V9            0.004467
V10           0.009824
V11          -0.006576
V12           0.010832
V13           0.000189
V14           0.012064
V15           0.000161
V16           0.007164
V17           0.011535
V18           0.003887
V19          -0.001178
V20          -0.000644
V21          -0.001235
V22          -0.000024
V23           0.000070
V24           0.000182
V25          -0.000072
V26          -0.000089
V27          -0.000295
V28          -0.000131
Amount       88.291022
Class         0.000000
dtype: float64

In [90]:
fraud.mean()

Time      80746.806911
V1           -4.771948
V2            3.623778
V3           -7.033281
V4            4.542029
V5           -3.151225
V6           -1.397737
V7           -5.568731
V8            0.570636
V9           -2.581123
V10          -5.676883
V11           3.800173
V12          -6.259393
V13          -0.109334
V14          -6.971723
V15          -0.092929
V16          -4.139946
V17          -6.665836
V18          -2.246308
V19           0.680659
V20           0.372319
V21           0.713588
V22           0.014049
V23          -0.040308
V24          -0.105130
V25           0.041449
V26           0.051648
V27           0.170575
V28           0.075667
Amount      122.211321
Class         1.000000
dtype: float64

In [91]:
legit_sam = legit.sample(n = 492)  # takes any n samples

In [92]:
new_dataset = pd.concat([legit_sam,fraud],axis=0)  # row wise

In [93]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
257111,158008.0,2.128249,-1.374844,-1.707666,-1.852084,1.133511,3.842815,-1.828260,1.022812,0.186773,...,0.431021,1.269103,0.114500,0.761775,-0.069613,0.044401,0.043228,-0.052045,14.95,0
119383,75429.0,0.950868,-0.816497,1.099782,0.215178,-1.269738,0.279128,-0.817922,0.387005,1.140469,...,-0.108053,-0.310520,0.067266,0.262381,-0.073929,0.938493,-0.045818,0.013944,90.76,0
110724,71946.0,1.123056,0.132600,0.428190,1.344290,-0.300240,-0.317196,0.068741,-0.009499,0.039493,...,-0.065231,-0.074064,-0.122895,0.350002,0.696724,-0.361980,0.015154,0.012945,30.19,0
249414,154395.0,-0.382965,1.408685,-1.529390,1.201790,-0.368316,0.925778,-0.062747,0.876465,-0.099221,...,0.000799,0.202571,0.269778,-1.047977,-0.789738,0.347174,-0.459186,-0.190827,110.12,0
90740,63147.0,1.004793,-0.672297,-0.445963,0.667430,1.533548,4.418254,-0.925142,1.128421,1.129803,...,-0.443313,-1.195307,-0.058603,0.999845,0.621183,-0.532953,0.059482,0.040705,100.44,0

In [94]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [95]:
new_dataset.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,95939.723577,-0.056541,-0.077812,-0.028021,-0.059419,0.029883,0.093007,0.039950,0.093928,-0.001281,...,-0.007351,-0.004080,-0.016158,0.039230,0.027803,0.030100,-0.001967,-0.007295,-0.022201,91.994533
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [96]:
X = new_dataset.drop(columns='Class', axis=1)
y = new_dataset['Class']

In [97]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, stratify=y, random_state=2) # 20 % data for test and 80 for train # stratifying Y for equal dis of 0s and 1s

In [98]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# fit the scaler to the train set, it will learn the parameters
scaler.fit(X_train)

# transform train and test sets
X_train_scaled = scaler.transform(X_train)  # transforms using z-score formula
X_test_scaled = scaler.transform(X_test)

In [99]:
X_train_scaled

array([[-1.27175496e+00, -2.93059370e+00,  2.56973783e+00, ...,
         1.50955980e+00,  1.00368853e+00, -4.18216261e-02],
       [-6.11885224e-01,  1.95121880e-01, -5.75688936e-02, ...,
         3.46506519e-01,  4.66356941e-01,  5.67615564e-01],
       [-4.06465666e-01,  6.69642044e-01, -8.26809640e-01, ...,
        -6.63172195e-02, -1.50086243e-03,  9.04901597e-02],
       ...,
       [ 8.08957755e-02,  4.37525574e-01,  1.55162228e-01, ...,
        -5.02528268e-01, -9.20559633e-01, -3.96672443e-01],
       [ 1.42280508e+00,  2.17243666e-01,  8.09619051e-01, ...,
         2.97564160e-01, -2.16034327e-01, -3.97496928e-01],
       [-1.07834666e+00,  6.45665303e-01, -6.12643239e-01, ...,
        -1.16782810e-01, -5.16437037e-02, -1.74599425e-01]])

In [100]:
X_train_scaled = pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [101]:
X_train_scaled

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
0,-1.271755,-2.930594,2.569738,-2.905568,1.198987,-3.077021,-1.929691,-2.060526,2.528700,-1.199470,...,1.292060,0.500170,-1.077884,-0.360858,0.225351,1.903820,-0.514836,1.509560,1.003689,-0.041822
1,-0.611885,0.195122,-0.057569,0.197988,0.238635,-0.081910,0.132269,0.233160,0.121929,-0.446944,...,0.742256,0.088736,-0.157695,0.505391,-0.378941,-0.310291,-0.640904,0.346507,0.466357,0.567616
2,-0.406466,0.669642,-0.826810,0.614957,-1.087669,-0.029810,-0.160292,0.330811,-0.129884,-0.200366,...,-0.289792,-0.189678,-0.283725,-0.071984,0.684996,0.412742,-0.512679,-0.066317,-0.001501,0.090490
3,-0.921076,-0.177099,0.171219,-0.041408,-0.617594,-0.167855,-0.700837,-0.050182,-0.429067,0.650413,...,-0.214143,0.620321,-0.434314,-0.231204,0.281990,0.089418,-2.289173,-1.231880,-2.400707,-0.084802
4,-1.434812,-2.370034,1.492470,-2.520016,2.815236,-1.266817,-0.790463,-2.070250,-0.229183,-2.562328,...,0.856995,-1.029152,0.646379,-0.315971,-1.753165,1.416221,1.675905,2.124091,-2.778888,-0.396672
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
683,1.033740,0.315371,-0.282894,0.579315,-0.648154,0.758663,-0.302169,0.698052,-0.117882,0.069427,...,-0.281338,-0.024519,0.585807,-0.247550,0.025627,0.385370,-1.205533,0.011367,0.224370,-0.314654
684,-1.641585,0.096539,0.437296,-0.157598,0.179754,-0.122953,-0.909329,-0.259591,0.278868,-0.058296,...,0.156878,0.108083,-0.437465,-0.023812,0.179275,0.021430,0.592135,0.336237,0.380842,-0.396672
685,0.080896,0.437526,0.155162,0.145516,-0.354182,1.169279,-0.596543,0.824171,-0.252012,0.963227,...,-0.185741,-0.341969,-0.773717,-0.368023,0.025839,0.812552,-1.608379,-0.502528,-0.920560,-0.396672
686,1.422805,0.217244,0.809619,-0.784048,1.707751,0.344363,-1.154211,-0.075193,0.262428,-1.336498,...,0.377106,0.058541,-0.472907,0.155824,-1.233202,-0.028452,1.036935,0.297564,-0.216034,-0.397497
687,-1.078347,0.645665,-0.612643,0.708228,-0.676955,0.125952,0.317137,0.349791,-0.056648,1.104430,...,-0.159947,-0.182821,-0.274731,-0.052978,-0.097015,0.144743,2.105450,-0.116783,-0.051644,-0.174599

In [102]:
from sklearn.linear_model import LogisticRegression

## Logistic Regression

In [103]:
lr_scaled = LogisticRegression()

In [104]:
lr_scaled.fit(X_train_scaled,y_train)

LogisticRegression()

In [105]:
y_pred_scaled = lr_scaled.predict(X_test_scaled)

In [106]:
from sklearn.metrics import classification_report, accuracy_score 
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import f1_score, matthews_corrcoef
from sklearn.metrics import confusion_matrix

In [107]:
print("Accuracy Score",accuracy_score(y_test,y_pred_scaled))
print("Precision score",precision_score(y_test,y_pred_scaled))
print("recall score",recall_score(y_test,y_pred_scaled))
print("Precision score",f1_score(y_test,y_pred_scaled))
print("recall score",matthews_corrcoef(y_test,y_pred_scaled))

Accuracy Score 0.9155405405405406
Precision score 0.9624060150375939
recall score 0.8648648648648649
Precision score 0.911032028469751
recall score 0.8353827222497626

## Random Forest regressor

In [108]:
from sklearn.ensemble import RandomForestClassifier
# random forest model creation
rfc = RandomForestClassifier()
rfc.fit(X_train_scaled,y_train)
# predictions
y_pred_scaled1 = rfc.predict(X_test_scaled)

In [109]:
print("Accuracy Score",accuracy_score(y_test,y_pred_scaled1))
print("Precision score",precision_score(y_test,y_pred_scaled1))
print("recall score",recall_score(y_test,y_pred_scaled1))
print("f1_score",f1_score(y_test,y_pred_scaled1))
print("matthews_corrcoef",matthews_corrcoef(y_test,y_pred_scaled1))

Accuracy Score 0.918918918918919
Precision score 0.9769230769230769
recall score 0.8581081081081081
f1_score 0.9136690647482014
matthews_corrcoef 0.8441040130225311

## Support vector machine

In [110]:
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn import svm

In [111]:
classifier = svm.SVC(kernel='linear')

In [112]:
classifier.fit(X_train_scaled, y_train)

SVC(kernel='linear')

In [113]:
prediction_SVM_all = classifier.predict(X_test_scaled)

In [114]:
print("Accuracy Score",accuracy_score(y_test,prediction_SVM_all))
print("Precision score",precision_score(y_test,prediction_SVM_all))
print("recall score",recall_score(y_test,prediction_SVM_all))
print("f1 score",f1_score(y_test,prediction_SVM_all))
print("matthew corrcoeff",matthews_corrcoef(y_test,prediction_SVM_all))

Accuracy Score 0.9155405405405406
Precision score 0.9624060150375939
recall score 0.8648648648648649
f1 score 0.911032028469751
matthew corrcoeff 0.8353827222497626